Update rubocop for newer versions
standout/Coding pull request #39
Opened 2020-09-08 08:53 UTC by frdrkolsson

Only allow 80 characters per line and enable all new cops by default

2020-09-08 08:57 UTC, alex-ross reviewed
Jag röstar för att frångå så lite defaults som möjligt. Lägger därför ingen approve just nu då jag hellre ser att vi följer max på radbredd enligt nya rubocop standarden.

2020-09-08 09:05 UTC, scmx approved these changes
👍 
Vi har en en lång erfarenhet i ruby community av 80-tecken per rad. Av goda anledningar. Sen tyckte rubocop-hq att det var en god idé att köra en omröstning. Slår vad om att denna omröstning inte var representativ för rubys community. Inte heller att alla som röstade förstod vinsten med 80 tecken.

Rubocop själva skriver över default till 80 tecken i sitt eget repo.

Känn inte att vi måste följa default. Det är inget magiskt rätt med det.

Tvärtom föreslår jag nästan revert av [`88ce77b` (#36)](https://github.com/standout/Coding/pull/36/commits/88ce77b6ab546c0cf0fb43e40b348e2a24c51398) som jag tyckte var ogenomtänkt och alltför snabbt mergad.

2020-09-08 09:13 UTC, frdrkolsson commented
> Jag röstar för att frångå så lite defaults som möjligt. Lägger därför ingen approve just nu då jag hellre ser att vi följer max på radbredd enligt nya rubocop standarden.

Sitter mer på Alberts sida där. 
Jag håller med om att hålla sig till de defaults som finns kan vara vettigt då det blir kontinuitet med många andra rails-projekt även utanför Standout, men 120 tecken är ju helt galet.

Läser man till och med rubocops officiella style-guide så skriver dem massa argument om att köra 80 tecken, och att man bara i riktigt speciella scenarion ska köra mer än det
https://rubystyle.guide/#max-line-length

2020-09-08 09:15 UTC, frdrkolsson commented
> Jag röstar för att frångå så lite defaults som möjligt. Lägger därför ingen approve just nu då jag hellre ser att vi följer max på radbredd enligt nya rubocop standarden.

> Jag röstar för att frångå så lite defaults som möjligt. Lägger därför ingen approve just nu då jag hellre ser att vi följer max på radbredd enligt nya rubocop standarden.

Sitter mer på @scmx sida där. 
Jag håller med om att hålla sig till de defaults som finns kan vara vettigt då det blir kontinuitet med många andra rails-projekt även utanför Standout, men 120 tecken är ju helt galet.

Läser man till och med rubocops officiella style-guide så skriver dem massa argument om att köra 80 tecken, och att man bara i riktigt speciella scenarion ska köra mer än det
https://rubystyle.guide/#max-line-length

2020-09-08 09:25 UTC, alex-ross commented
@frdrkolsson tycker det är lite humoristiskt att du i committen @scmx länkade till försökte smyga in 120 i bredd 😁😇.

Alla vinster med 80 tecken numera skulle jag hävda är personliga åsikter och vad man föredrar. På större skärmar är det ju enklare att få 3 filer bredvid varandra utan konstiga radbrytningar. Men från början kommer det väll från gamla hålkortstiden.

Har inget emot 80 tecken i bredd om det blir majoritet, det är ju lätt att committa till då man typ alltid kört på det.

Men att köra 120 som en ny standard tycker jag också låter lite spännande och kräver mindre config :) Jag gillar att ha starka argument för frångå standard. Men om alla tycker att det "känns" bättre så är det tillräckligt för mig.

2020-09-08 09:26 UTC, alex-ross commented
Jag hade nog helst av allt önskat att man bara körde exklude på fillistor i regler för att exkludera typ genererade filer och sen standard på resten :)

2020-09-08 09:46 UTC, robert-sjoblom commented
Ärligt talat så lägger vi för mycket tid på att diskutera det här, är det här tredje gången vi gör uppdateringar i år, eller är det "bara" andra?

Bryr mig inte så mycket om det egentligen. 120 tecken är för långt, 80 passar bra imo, men annars bara kör på nåt (eller kör med https://github.com/testdouble/standard så vi *slipper* de här diskussionerna hela tiden) och framför allt **spika** inställningarna så vi slipper det här hela tiden.

2020-09-08 09:48 UTC, robert-sjoblom requested changes
Tycker inte vi ska enablea NewCops, tycker vi ska disablea dem.

2020-09-08 10:00 UTC, scmx commented
NewCops skulle man kunna köra false här tillsvidare. Jag lade in true på Prido. Får väl se vad de kommer på för nya regler om det var bra eller ej. Man kan prova i något repo och se.

Jag tänker så här. Prova sådana ändringar som overrides i ett repo först innan man aktiverar på alla

2020-09-08 11:05 UTC, svenne87 approved these changes

2020-09-08 11:21 UTC, alex-ross approved these changes
Jag lägger en approve för att jag tolkar det efter diskussion på kontoret som att det ger mest developer happiness än att köra 120.

2020-09-09 08:18 UTC, frdrkolsson commented
@scmx Håller med dig och @robert-sjoblom. Avaktiverade nya cops, så slipper man få meddelandet att "Det finns nya tops som du inte kör 👀", men så kan man aktivera per projekt tills kanske version 1 kommer ut!

2020-09-09 08:23 UTC, robert-sjoblom commented on ruby/rubocop.yml
> +  NewCops: disabled
`disable`, inte `disabled`

2020-09-09 08:23 UTC, robert-sjoblom requested changes
Enligt kommentar.

2020-09-09 08:26 UTC, merged